"""Centralized demo data for Tyler Chen — used by all mock document templates."""

TYLER = {
    # Identity
    "legal_name": "Tyler James Chen",
    "dob": "1993-08-14",
    "dob_display": "08/14/1993",
    "ssn": "***-**-7823",
    "ssn_last4": "7823",
    "address": "142 Asylum St, Hartford, CT 06103",
    "city": "Hartford",
    "state": "CT",
    "zip": "06103",
    "phone": "(860) 555-0147",
    "gender": "Male",
    "height": "5'10\"",
    "weight": "175",
    "eyes": "Brown",
    "hair": "Black",
    # Criminal justice
    "state_of_release": "CT",
    "release_date": "2026-02-15",
    "release_date_display": "02/15/2026",
    "parole_end": "2028-02-15",
    "parole_end_display": "02/15/2028",
    "offense": "Larceny in the Third Degree",
    "offense_statute": "CGS §53a-124",
    "offense_class": "Class A Misdemeanor",
    "sentence": "3 years incarceration, 2 years parole supervision",
    "case_number": "HHD-CR-22-0741256",
    "docket_number": "HHD-CR22-0741256-S",
    "inmate_number": "387291",
    "facility": "Carl Robinson Correctional Institution",
    # Supervision
    "po_name": "Maria Gonzalez",
    "po_title": "Parole Officer II",
    "po_phone": "(860) 566-4800",
    "po_office": "CT Department of Correction, Parole & Community Services",
    "po_address": "95 Washington St, Hartford, CT 06106",
    "curfew_start": "22:00",
    "curfew_end": "06:00",
    "reporting_frequency": "biweekly",
    "next_reporting_date": "2026-04-10",
    "drug_testing_required": True,
    "drug_testing_frequency": "random",
    "electronic_monitoring": False,
    "geographic_restrictions": False,
    "no_contact_orders": False,
    "mandatory_treatment": False,
    # Financial
    "restitution_owed": True,
    "restitution_amount": 2400.00,
    "restitution_monthly_payment": 100.00,
    "outstanding_fines": True,
    "outstanding_fines_amount": 350.00,
    "court_costs": 225.00,
    # Employment / Education
    "certifications": ["Forklift Operator", "OSHA-10"],
    "trade_skills": ["carpentry", "forklift operation"],
    "has_ged": True,
    "ged_date": "2024-06-15",
    "ged_date_display": "06/15/2024",
    "has_drivers_license": False,
    "employment_status": "actively_looking",
    "felony_category": "non_violent",
    # Health
    "diagnoses": ["hypertension"],
    "medications": [{"name": "Lisinopril", "dosage": "10mg", "frequency": "once daily"}],
    "disability_status": False,
    "substance_use_disorder": False,
    "mental_health_diagnoses": [],
    "has_medicaid": True,
    "medicaid_id": "CT-MA-9928174",
    # Benefits
    "snap_enrolled": True,
    "snap_case_number": "DSS-2026-441782",
    "snap_monthly_amount": 234,
    "snap_start_date": "2026-03-01",
    "snap_recertification_date": "2026-09-01",
    "veteran_status": False,
    # Forklift cert details
    "forklift_cert_number": "FL-CT-2024-08817",
    "forklift_cert_date": "2024-04-22",
    "forklift_cert_expiry": "2027-04-22",
    "forklift_equipment_types": [
        "Class I — Electric Motor Rider Trucks",
        "Class IV — Internal Combustion Engine Trucks (Cushion Tires)",
        "Class V — Internal Combustion Engine Trucks (Pneumatic Tires)",
    ],
    "forklift_issuing_org": "National Safety Compliance, Inc.",
    # Court personnel (fictional)
    "judge_name": "Hon. Patricia A. Mullins",
    "judge_title": "Judge, Superior Court",
    "clerk_name": "Robert J. Hernandez",
    "ged_registrar": "Dr. Karen L. Bates",
    "physician_name": "Dr. Anita R. Patel",
    "physician_title": "Internal Medicine",
    "clinic_name": "Community Health Center of Hartford",
    "clinic_address": "635 Main St, Hartford, CT 06103",
    "dss_caseworker": "James T. Morrison",
}
